package model;
// Generated Nov 30, 2016 1:53:31 PM by Hibernate Tools 4.3.1



/**
 * ConsultaExame generated by hbm2java
 */
public class ConsultaExame  implements java.io.Serializable {


     private Integer idconsultaExame;
     private Exame exame;
     private Prontuario prontuario;

    public ConsultaExame() {
    }

	
    public ConsultaExame(Prontuario prontuario) {
        this.prontuario = prontuario;
    }
    public ConsultaExame(Exame exame, Prontuario prontuario) {
       this.exame = exame;
       this.prontuario = prontuario;
    }
   
    public Integer getIdconsultaExame() {
        return this.idconsultaExame;
    }
    
    public void setIdconsultaExame(Integer idconsultaExame) {
        this.idconsultaExame = idconsultaExame;
    }
    public Exame getExame() {
        return this.exame;
    }
    
    public void setExame(Exame exame) {
        this.exame = exame;
    }
    public Prontuario getProntuario() {
        return this.prontuario;
    }
    
    public void setProntuario(Prontuario prontuario) {
        this.prontuario = prontuario;
    }




}


