package model;
// Generated Nov 30, 2016 1:53:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Especie generated by hbm2java
 */
public class Especie  implements java.io.Serializable {


     private Integer idespecie;
     private String descricao;
     private String nomeCientifico;
     private Set racas = new HashSet(0);

    public Especie() {
    }

    public Especie(String descricao, String nomeCientifico, Set racas) {
       this.descricao = descricao;
       this.nomeCientifico = nomeCientifico;
       this.racas = racas;
    }
   
    public Integer getIdespecie() {
        return this.idespecie;
    }
    
    public void setIdespecie(Integer idespecie) {
        this.idespecie = idespecie;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public String getNomeCientifico() {
        return this.nomeCientifico;
    }
    
    public void setNomeCientifico(String nomeCientifico) {
        this.nomeCientifico = nomeCientifico;
    }
    public Set getRacas() {
        return this.racas;
    }
    
    public void setRacas(Set racas) {
        this.racas = racas;
    }




}


