package model;
// Generated Nov 30, 2016 1:53:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Exame generated by hbm2java
 */
public class Exame  implements java.io.Serializable {


     private Integer idexame;
     private String nome;
     private String area;
     private Set items = new HashSet(0);
     private Set consultaExames = new HashSet(0);

    public Exame() {
    }

    public Exame(String nome, String area, Set items, Set consultaExames) {
       this.nome = nome;
       this.area = area;
       this.items = items;
       this.consultaExames = consultaExames;
    }
   
    public Integer getIdexame() {
        return this.idexame;
    }
    
    public void setIdexame(Integer idexame) {
        this.idexame = idexame;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }
    public Set getItems() {
        return this.items;
    }
    
    public void setItems(Set items) {
        this.items = items;
    }
    public Set getConsultaExames() {
        return this.consultaExames;
    }
    
    public void setConsultaExames(Set consultaExames) {
        this.consultaExames = consultaExames;
    }




}


