package model;
// Generated Nov 30, 2016 1:53:31 PM by Hibernate Tools 4.3.1



/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private Integer idfuncionario;
     private Usuario usuario;
     private Integer funcao;

    public Funcionario() {
    }

    public Funcionario(Usuario usuario, Integer funcao) {
       this.usuario = usuario;
       this.funcao = funcao;
    }
   
    public Integer getIdfuncionario() {
        return this.idfuncionario;
    }
    
    public void setIdfuncionario(Integer idfuncionario) {
        this.idfuncionario = idfuncionario;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Integer getFuncao() {
        return this.funcao;
    }
    
    public void setFuncao(Integer funcao) {
        this.funcao = funcao;
    }




}


