package model;
// Generated Nov 30, 2016 1:53:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * GrupoAcesso generated by hbm2java
 */
public class GrupoAcesso  implements java.io.Serializable {

     private Integer idgrupoAcesso;
     private String descricao;
     private Set usuarios = new HashSet(0);

    public GrupoAcesso() {
    }

    public GrupoAcesso(String descricao, Set usuarios) {
       this.descricao = descricao;
       this.usuarios = usuarios;
    }
   
    public Integer getIdgrupoAcesso() {
        return this.idgrupoAcesso;
    }
    
    public void setIdgrupoAcesso(Integer idgrupoAcesso) {
        this.idgrupoAcesso = idgrupoAcesso;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


