package model;
// Generated Nov 30, 2016 1:53:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Item generated by hbm2java
 */
public class Item  implements java.io.Serializable {


     private Integer iditem;
     private Exame exame;
     private String nome;
     private String referencia;
     private Set resultadoItems = new HashSet(0);

    public Item() {
    }

	
    public Item(Exame exame) {
        this.exame = exame;
    }
    public Item(Exame exame, String nome, String referencia, Set resultadoItems) {
       this.exame = exame;
       this.nome = nome;
       this.referencia = referencia;
       this.resultadoItems = resultadoItems;
    }
   
    public Integer getIditem() {
        return this.iditem;
    }
    
    public void setIditem(Integer iditem) {
        this.iditem = iditem;
    }
    public Exame getExame() {
        return this.exame;
    }
    
    public void setExame(Exame exame) {
        this.exame = exame;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }
    public Set getResultadoItems() {
        return this.resultadoItems;
    }
    
    public void setResultadoItems(Set resultadoItems) {
        this.resultadoItems = resultadoItems;
    }




}


