package model;
// Generated Nov 30, 2016 1:53:31 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Prontuario generated by hbm2java
 */
public class Prontuario  implements java.io.Serializable {


     private Integer idprontuario;
     private Pet pet;
     private Veterinario veterinario;
     private Date data;
     private String observacao;
     private Boolean realizado;
     private Set consultaExames = new HashSet(0);

    public Prontuario() {
    }

    public Prontuario(Pet pet, Veterinario veterinario, Date data, String observacao, Boolean realizado, Set consultaExames) {
       this.pet = pet;
       this.veterinario = veterinario;
       this.data = data;
       this.observacao = observacao;
       this.realizado = realizado;
       this.consultaExames = consultaExames;
    }
   
    public Integer getIdprontuario() {
        return this.idprontuario;
    }
    
    public void setIdprontuario(Integer idprontuario) {
        this.idprontuario = idprontuario;
    }
    public Pet getPet() {
        return this.pet;
    }
    
    public void setPet(Pet pet) {
        this.pet = pet;
    }
    public Veterinario getVeterinario() {
        return this.veterinario;
    }
    
    public void setVeterinario(Veterinario veterinario) {
        this.veterinario = veterinario;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }
    public Boolean getRealizado() {
        return this.realizado;
    }
    
    public void setRealizado(Boolean realizado) {
        this.realizado = realizado;
    }
    public Set getConsultaExames() {
        return this.consultaExames;
    }
    
    public void setConsultaExames(Set consultaExames) {
        this.consultaExames = consultaExames;
    }




}


