package model;
// Generated Nov 30, 2016 1:53:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proprietario generated by hbm2java
 */
public class Proprietario  implements java.io.Serializable {


     private Integer idproprietario;
     private String nome;
     private String endereco;
     private String telefone;
     private String cpf;
     private Set pets = new HashSet(0);

    public Proprietario() {
    }

	
    public Proprietario(String cpf) {
        this.cpf = cpf;
    }
    public Proprietario(String nome, String endereco, String telefone, String cpf, Set pets) {
       this.nome = nome;
       this.endereco = endereco;
       this.telefone = telefone;
       this.cpf = cpf;
       this.pets = pets;
    }
   
    public Integer getIdproprietario() {
        return this.idproprietario;
    }
    
    public void setIdproprietario(Integer idproprietario) {
        this.idproprietario = idproprietario;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public Set getPets() {
        return this.pets;
    }
    
    public void setPets(Set pets) {
        this.pets = pets;
    }




}


