package model;
// Generated Nov 30, 2016 1:53:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Raca generated by hbm2java
 */
public class Raca  implements java.io.Serializable {


     private Integer idraca;
     private Especie especie;
     private String descricao;
     private Set pets = new HashSet(0);

    public Raca() {
    }

    public Raca(Especie especie, String descricao, Set pets) {
       this.especie = especie;
       this.descricao = descricao;
       this.pets = pets;
    }
   
    public Integer getIdraca() {
        return this.idraca;
    }
    
    public void setIdraca(Integer idraca) {
        this.idraca = idraca;
    }
    public Especie getEspecie() {
        return this.especie;
    }
    
    public void setEspecie(Especie especie) {
        this.especie = especie;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set getPets() {
        return this.pets;
    }
    
    public void setPets(Set pets) {
        this.pets = pets;
    }




}


