package model;
// Generated Nov 30, 2016 1:53:31 PM by Hibernate Tools 4.3.1



/**
 * ResultadoItem generated by hbm2java
 */
public class ResultadoItem  implements java.io.Serializable {


     private Integer idresultadoItem;
     private Item item;

    public ResultadoItem() {
    }

    public ResultadoItem(Item item) {
       this.item = item;
    }
   
    public Integer getIdresultadoItem() {
        return this.idresultadoItem;
    }
    
    public void setIdresultadoItem(Integer idresultadoItem) {
        this.idresultadoItem = idresultadoItem;
    }
    public Item getItem() {
        return this.item;
    }
    
    public void setItem(Item item) {
        this.item = item;
    }




}


