package model;
// Generated Nov 30, 2016 1:53:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idusuario;
     private GrupoAcesso grupoAcesso;
     private String username;
     private String senha;
     private String nome;
     private String endereco;
     private String telefone;
     private String cpf;

    public Usuario() {
    }

    public Usuario(GrupoAcesso grupoAcesso, String username, String senha, String nome, String endereco, String telefone, String cpf, Set veterinarios, Set funcionarios) {
       this.grupoAcesso = grupoAcesso;
       this.username = username;
       this.senha = senha;
       this.nome = nome;
       this.endereco = endereco;
       this.telefone = telefone;
       this.cpf = cpf;
    }
   
    public Integer getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(Integer idusuario) {
        this.idusuario = idusuario;
    }
    public GrupoAcesso getGrupoAcesso() {
        return this.grupoAcesso;
    }
    
    public void setGrupoAcesso(GrupoAcesso grupoAcesso) {
        this.grupoAcesso = grupoAcesso;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
}


