package model;
// Generated Nov 30, 2016 1:53:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Veterinario generated by hbm2java
 */
public class Veterinario  implements java.io.Serializable {


     private Integer idveterinario;
     private Usuario usuario;
     private String crv;
     private String especialidade;
     private Set prontuarios = new HashSet(0);

    public Veterinario() {
    }

    public Veterinario(Usuario usuario, String crv, String especialidade, Set prontuarios) {
       this.usuario = usuario;
       this.crv = crv;
       this.especialidade = especialidade;
       this.prontuarios = prontuarios;
    }
   
    public Integer getIdveterinario() {
        return this.idveterinario;
    }
    
    public void setIdveterinario(Integer idveterinario) {
        this.idveterinario = idveterinario;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getCrv() {
        return this.crv;
    }
    
    public void setCrv(String crv) {
        this.crv = crv;
    }
    public String getEspecialidade() {
        return this.especialidade;
    }
    
    public void setEspecialidade(String especialidade) {
        this.especialidade = especialidade;
    }
    public Set getProntuarios() {
        return this.prontuarios;
    }
    
    public void setProntuarios(Set prontuarios) {
        this.prontuarios = prontuarios;
    }




}


